#ifndef GLOBAL_DECLARATIONS_H
#define GLOBAL_DECLARATIONS_H

#define SINGLETON_CLASS(_CLASS)\
static _CLASS& getInstance()\
{\
	static _CLASS Instance;\
	return Instance;\
}\
_CLASS(const _CLASS&) = delete;\
_CLASS& operator=(const _CLASS&) = delete;

//#define ENEMYPROJECTILE_COLLISION_BITMASK 0x000001
//#define PLAYER_COLLISION_BITMASK  0x000010
//#define UNUSED_COLLISION_BITMASK0 0x000011
//#define UNUSED_COLLISION_BITMASK1 0x001000
//#define UNUSED_COLLISION_BITMASK2 0x010000
//#define UNUSED_COLLISION_BITMASK3 0x100000
//#define ALL_COLLISION_BITMASK4 0x111111

#endif